#pragma once

#include "WRL.h"
#include <dwrite.h>

#include <array>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "Canvas.h"
#include "TextRenderer.h"
#include "TextDrawContext.h"
#include "DWriteLayoutRenderer.h"


class TextCodex
{
    friend class Text::TextDrawContext;
    friend class Text::TextRenderer;
    friend class Text::DWriteLayoutRenderer;

public:
    static TextCodex& Get() noexcept;

    // Create a shared DWrite factory and register a custom FontCollectionLoader.
    void Init();

    // Rent a TextRenderer from the pool; returned and reset when TextDrawContext is destructed.
    Text::TextDrawContext BeginDraw();

private:
    TextCodex() = default;

    // -------------------------------------------------------------------------
    // Text::TextDrawContext — Rendering session and TextRenderer pool
    // -------------------------------------------------------------------------

    /** Acquire the first available slot in the pool; construct TextRenderer if necessary. */
    std::size_t AcquireTextRendererSlot_();

    /** Release the slot and clear the TextRenderer's layout cache to avoid state changes across sessions. */
    void ReleaseTextRendererSlot_(std::size_t slot) noexcept;

    // -------------------------------------------------------------------------
    // Text::TextRenderer — Layout phase: factory, TextFormat, custom font collections
    // -------------------------------------------------------------------------

    IDWriteFactory* GetFactory() const noexcept { return factory_.Get(); }

    
    // TextFormat on the system font collection (cached by family + size + weight/style/stretch).
    Microsoft::WRL::ComPtr<IDWriteTextFormat> GetSystemFormat(
        const std::wstring& fontFamily,
        float fontSize,
        DWRITE_FONT_WEIGHT weight = DWRITE_FONT_WEIGHT_NORMAL,
        DWRITE_FONT_STYLE style = DWRITE_FONT_STYLE_NORMAL,
        DWRITE_FONT_STRETCH stretch = DWRITE_FONT_STRETCH_NORMAL);

    
    // TextFormat based on a custom FontCollection (primary font is a single file on disk; with caching).
    Microsoft::WRL::ComPtr<IDWriteTextFormat> GetFileTextFormat(
        const std::wstring& fontFilePath,
        float fontSize,
        DWRITE_FONT_WEIGHT weight = DWRITE_FONT_WEIGHT_NORMAL,
        DWRITE_FONT_STYLE style = DWRITE_FONT_STYLE_NORMAL,
        DWRITE_FONT_STRETCH stretch = DWRITE_FONT_STRETCH_NORMAL);

    // Create a custom font collection from a single file (path-level caching).
    Microsoft::WRL::ComPtr<IDWriteFontCollection> GetCustomFontCollectionFromFile(const std::wstring& fontFilePath);
    // Create a custom font collection from multiple files (path order affects family enumeration order; whole set key caching).
    Microsoft::WRL::ComPtr<IDWriteFontCollection> GetCustomFontCollectionFromFiles(const std::vector<std::wstring>& fontFilePaths);
    // Get the display name of the first family in the collection (used for the family parameter in CreateTextFormat).
    std::wstring GetFirstFamilyName(IDWriteFontCollection* collection);
    // Create a FontFace from a font file (path-level caching; not the main path for TextLayout, used for glyph/metrics extensions).
    Microsoft::WRL::ComPtr<IDWriteFontFace> GetFontFaceFromFile(const std::wstring& fontFilePath);

    // -------------------------------------------------------------------------
    // Text::TextRenderer — Internal: Custom collection keys and primary family name resolution
    // -------------------------------------------------------------------------

    // Encode a list of paths into a key for unordered_map (prefix separator for multiple files to avoid conflicts with single paths).
    static std::wstring MakeCollectionCacheKey_(const std::vector<std::wstring>& paths);

    // Actual entry point for CreateCustomFontCollection (with customCollectionsByKey_ cache).
    Microsoft::WRL::ComPtr<IDWriteFontCollection> GetCustomFontCollectionFromPaths_(const std::vector<std::wstring>& paths);

    // Cache for the primary family name of a single-file font, reducing repeated queries to LocalizedStrings.
    std::wstring ResolvePrimaryFamilyName_(const std::wstring& singleFilePath, IDWriteFontCollection* collection);

    // -------------------------------------------------------------------------
    // Text::DWriteLayoutRenderer — IDWriteTextLayout::Draw callback: glyph rasterization
    // -------------------------------------------------------------------------

    /** Blend the glyphRun generated by DWrite into the Canvas using alpha texture. */
    void DrawGlyphRunToCanvas(
        Canvas& canvas,
        float baselineOriginX,
        float baselineOriginY,
        const DWRITE_GLYPH_RUN& glyphRun,
        Color color,
        bool clipEnabled = false,
        int clipX0 = 0,
        int clipY0 = 0,
        int clipX1 = 0,
        int clipY1 = 0);

    // -------------------------------------------------------------------------
    // Cache key types (for systemFormats_ / fileFormats_ usage)
    // -------------------------------------------------------------------------

    struct SystemFormatKey
    {
        std::wstring family;
        float size = 0.0f;
        DWRITE_FONT_WEIGHT weight = DWRITE_FONT_WEIGHT_NORMAL;
        DWRITE_FONT_STYLE style = DWRITE_FONT_STYLE_NORMAL;
        DWRITE_FONT_STRETCH stretch = DWRITE_FONT_STRETCH_NORMAL;

        bool operator==(const SystemFormatKey& o) const noexcept;
    };

    struct SystemFormatKeyHash
    {
        size_t operator()(const SystemFormatKey& k) const noexcept;
    };

    struct FileFormatKey
    {
        std::wstring path;
        float size = 0.0f;
        DWRITE_FONT_WEIGHT weight = DWRITE_FONT_WEIGHT_NORMAL;
        DWRITE_FONT_STYLE style = DWRITE_FONT_STYLE_NORMAL;
        DWRITE_FONT_STRETCH stretch = DWRITE_FONT_STRETCH_NORMAL;
        bool operator==(const FileFormatKey& o) const noexcept;
    };

    struct FileFormatKeyHash
    {
        size_t operator()(const FileFormatKey& k) const noexcept;
    };

    // -------------------------------------------------------------------------
    // Members: lifecycle, DWrite objects, caches, TextRenderer pool
    // -------------------------------------------------------------------------

    static constexpr std::size_t kTextRendererPoolCap = 8;

    bool initialized_ = false;
    Microsoft::WRL::ComPtr<IDWriteFactory> factory_;

    // Must remain alive until process exit; used by CreateCustomFontCollection.
    Microsoft::WRL::ComPtr<IDWriteFontCollectionLoader> customCollectionLoader_;

    std::unordered_map<std::wstring, Microsoft::WRL::ComPtr<IDWriteFontCollection>> customCollectionsByKey_;
    std::unordered_map<std::wstring, std::wstring> primaryFamilyNameByKey_;

    std::unordered_map<SystemFormatKey, Microsoft::WRL::ComPtr<IDWriteTextFormat>, SystemFormatKeyHash> systemFormats_;
    std::unordered_map<FileFormatKey, Microsoft::WRL::ComPtr<IDWriteTextFormat>, FileFormatKeyHash> fileFormats_;
    std::unordered_map<std::wstring, Microsoft::WRL::ComPtr<IDWriteFontFace>> fontFacesByPath_;

    std::array<bool, kTextRendererPoolCap> textRendererSlotUsed_{};
    std::array<std::unique_ptr<Text::TextRenderer>, kTextRendererPoolCap> textRendererPool_{};
};
